### ISSUE TITLE
KvsProcessRecording Lambda Failure

### ISSUE THREAD

**Issue by jcbuilds** [amazon-connect/voicemail-for-amazon-connect#106]
Hello,

We are currently experiencing issues with the KvsProcessRecording Lambda Function. The voicemail recordings are not being uploaded to the S3 Bucket, and the voicemail contact entries are not being logged in DynamoDB. The Java source codes used are the out-of-the-box jar file provided by the solution, and the Lambda policies used are also the ones provided in the CloudFormation template.

Is there something we are missing here? What could possibly be the root cause of this error?

Here are the logs from CloudWatch:

```
INIT_START Runtime Version: java:8.al2.v20	Runtime Version ARN: arn:aws:lambda:us-west-2::runtime:1057533df8bdb746a7425a7bd6e3e63712afd0b6d8c873ed226b44ac97fcfb69
Unexpected problem occured during version sanity check
Reported exception:
java.lang.AbstractMethodError: org.apache.logging.slf4j.SLF4JServiceProvider.getRequestedApiVersion()Ljava/lang/String;
at org.slf4j.LoggerFactory.versionSanityCheck(LoggerFactory.java:297)
at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:141)
at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:421)
at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:407)
at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:356)
at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:382)
at com.amazonaws.kvstream.KVSProcessRecordingLambda.<clinit>(KVSProcessRecordingLambda.java:39)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
at lambdainternal.HandlerInfo.fromString(HandlerInfo.java:33)
at lambdainternal.AWSLambda.findUserMethods(AWSLambda.java:112)
at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:234)
at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:201)
at lambdainternal.AWSLambda.main(AWSLambda.java:196)
Transforming org/apache/logging/log4j/core/lookup/JndiLookup (lambdainternal.CustomerClassLoader@37bba400)
START RequestId: abb1d238-7ccb-435f-a40d-f0acb397b80f Version: $LATEST

Processing CTR Event
Record Data: { XXXX JSON Object Here XXXX }

log4j:ERROR Could not instantiate class [com.amazonaws.services.lambda.runtime.log4j.LambdaAppender].
java.lang.ClassNotFoundException: com.amazonaws.services.lambda.runtime.log4j.LambdaAppender. Current classpath: file:/var/task/
at lambdainternal.CustomerClassLoader.findClass(CustomerClassLoader.java:63)
at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:264)
at org.apache.log4j.helpers.Loader.loadClass(Loader.java:190)
at org.apache.log4j.helpers.OptionConverter.instantiateByClassName(OptionConverter.java:304)
at org.apache.log4j.helpers.OptionConverter.instantiateByKey(OptionConverter.java:123)
at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:755)
at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:738)
at org.apache.log4j.PropertyConfigurator.configureRootCategory(PropertyConfigurator.java:630)
at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:516)
at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:577)
at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:504)
at org.apache.log4j.LogManager.<clinit>(LogManager.java:119)
at org.apache.log4j.Logger.getLogger(Logger.java:101)
at org.apache.commons.logging.impl.Log4JLogger.getLogger(Log4JLogger.java:262)
at org.apache.commons.logging.impl.Log4JLogger.<init>(Log4JLogger.java:108)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.apache.commons.logging.impl.LogFactoryImpl.createLogFromClass(LogFactoryImpl.java:1025)
at org.apache.commons.logging.impl.LogFactoryImpl.discoverLogImplementation(LogFactoryImpl.java:844)
at org.apache.commons.logging.impl.LogFactoryImpl.newInstance(LogFactoryImpl.java:541)
at org.apache.commons.logging.impl.LogFactoryImpl.getInstance(LogFactoryImpl.java:292)
at org.apache.commons.logging.impl.LogFactoryImpl.getInstance(LogFactoryImpl.java:269)
at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:657)
at com.amazonaws.AmazonWebServiceClient.<clinit>(AmazonWebServiceClient.java:82)
at com.amazonaws.transcribe.TranscribeService.<init>(TranscribeService.java:31)
at com.amazonaws.kvstream.KVSProcessRecordingLambda.processData(KVSProcessRecordingLambda.java:70)
at com.amazonaws.kvstream.KVSProcessRecordingLambda.handleRequest(KVSProcessRecordingLambda.java:49)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at lambdainternal.EventHandlerLoader$PojoMethodRequestHandler.handleRequest(EventHandlerLoader.java:288)
at lambdainternal.EventHandlerLoader$PojoHandlerAsStreamHandler.handleRequest(EventHandlerLoader.java:205)
at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:905)
at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:266)
at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:201)
at lambdainternal.AWSLambda.main(AWSLambda.java:196)
log4j:ERROR Could not instantiate appender named "LAMBDA".
log4j:ERROR Could not find value for key log4j.appender.CONSOLE
log4j:ERROR Could not instantiate appender named "CONSOLE".
2023-06-30 09:47:16 abb1d238-7ccb-435f-a40d-f0acb397b80f INFO  AudioStreamService:60 - StreamARN=arn:aws:kinesisvideo:us-west-2:XXXXXXXXX:stream/XXX-connect-XXX-connect-instance-contact-94664146-c348-4f1a-bc75-512b374e0e7a/1686734607288, startFragmentNum=91343852333181432392682062655060026792295737920, contactId=3a77cb5d-d02f-4f26-896f-88b92551f7eftranscribeEnabled=true, encryptionEnabled=true
Save Path: /tmp/3a77cb5d-d02f-4f26-896f-88b92551f7ef_1688118436.raw Start Selector Type: FRAGMENT_NUMBER
java.lang.NullPointerException
END RequestId: abb1d238-7ccb-435f-a40d-f0acb397b80f
```

**Comment by virtualgill** [comment]
Hi @jcbuilds 
You can ignore the log4j error part, it's expected and not causing any problems in and of itself. 
Here are some things to double check:
- In the Connect console, Live media streaming is turned on in Data Storage, and Data streaming is enabled in Data Streaming and the CTR being sent to the right Kinesis Steam
- If you decided to use an existing Kinesis Data stream (configured before deploying this), the IAM Role for the KvsProcessRecord lambda was updated with your own rather than the one created by the CFN Stack
- If any changes were made to Flows, ensure that the Media Streaming blocks are still there and enabled (with only From the customer checked) at the right place.

**Comment by jcbuilds** [comment]
Thanks for the response, @virtualgill. 

Upon inspecting, I can confirm that the Live media streaming is enabled, Data streaming is enabled, and CTR is being sent to the Kinesis Data Stream created from the template. Media Stream blocks are also present in the Contact Flows (with only From the Customer checked).

To add, here is also an excerpt from the CloudTrail logs from the following event:
- Event name: `GetDataEndpoint`
- Event source: `kinesisvideo.amazonaws.com`
- Username: `xxx-xxxxxxxx-KvsProcessRecording (name of the Lambda Function)`

```
"userAgent": "aws-sdk-java/1.12.286 Linux/4.14.255-311-248.529.amzn2.x86_64 OpenJDK_64-Bit_Server_VM/25.372-b07 java/1.8.0_372 vendor/Amazon.com_Inc. cfg/retry-mode/legacy exec-env/AWS_Lambda_java8.al2",
    "errorCode": "AccessDenied",
    "errorMessage": "User: arn:aws:sts::XXXXXXXXX:assumed-role/XXX-voicemail-solution-Vo-KvsProcessRecordingIamRo-1WJDCJLNDVZFO/XXX-xxxxxxx-KvsProcessRecording is not authorized to perform: kinesisvideo:GetDataEndpoint on resource: xxx-connect-xxx-connect-instance-contact-94664146-c348-4f1a-bc75-512b374e0e7a",
    "requestParameters": null,
    "responseElements": null,
```

I noticed that there are `AccessDenied` errors present in the trail although the execution role for the KvsProcesRecording Lambda allows the "kinesisvideo:GetDataEndpoint" function on "*" resources. 
The requestParameters are also `null`. In a successful run, it has `streamName` and `apiName` attributes.

Do you think this might be caused by account-level SCP permission configurations or KVS configurations? Let me know if you have other ideas as to why the solution is behaving this way. Thanks for your help!

**Comment by virtualgill** [comment]
I would recommend checking the account or Organisation SCPs, especially if this had worked previously.

**Comment by jcbuilds** [comment]
Thank you! It was, indeed, the recent changes in the account's SCP that caused the errors encountered. I'm now marking this issue as closed.
